In [1]:
import numpy as np

# 创建示例矩阵
matrix = np.random.randint(0, 10, (8, 8))
print("原始矩阵：")
print(matrix)

# 计算每行的和
row_sums = matrix.sum(axis=1)
print("每行的和：")
print(row_sums)

# 计算每个值与它所在行值的和的比值并构造新矩阵
ratios = matrix / row_sums[:, np.newaxis]
print("每个值与它所在行值的和的比值构成的新矩阵：")
print(ratios)

原始矩阵：
[[3 2 5 4 1 0 8 1]
 [5 0 5 3 9 0 6 3]
 [5 5 5 9 7 7 4 9]
 [6 5 9 5 9 5 8 8]
 [3 6 6 3 9 7 6 1]
 [2 4 8 7 4 7 7 1]
 [2 6 3 8 4 3 7 1]
 [4 2 4 3 0 9 9 7]]
每行的和：
[24 31 51 55 41 40 34 38]
每个值与它所在行值的和的比值构成的新矩阵：
[[0.125      0.08333333 0.20833333 0.16666667 0.04166667 0.
  0.33333333 0.04166667]
 [0.16129032 0.         0.16129032 0.09677419 0.29032258 0.
  0.19354839 0.09677419]
 [0.09803922 0.09803922 0.09803922 0.17647059 0.1372549  0.1372549
  0.07843137 0.17647059]
 [0.10909091 0.09090909 0.16363636 0.09090909 0.16363636 0.09090909
  0.14545455 0.14545455]
 [0.07317073 0.14634146 0.14634146 0.07317073 0.2195122  0.17073171
  0.14634146 0.02439024]
 [0.05       0.1        0.2        0.175      0.1        0.175
  0.175      0.025     ]
 [0.05882353 0.17647059 0.08823529 0.23529412 0.11764706 0.08823529
  0.20588235 0.02941176]
 [0.10526316 0.05263158 0.10526316 0.07894737 0.         0.23684211
  0.23684211 0.18421053]]


In [5]:
top3_indices = np.argsort(ratios, axis=1)[:, -3:]
    # 每行最大的三个值
top3_values = np.sort(ratios, axis=1)[:, -3:]
print("每行最大的三个值的索引：")
print(top3_indices)
print(top3_values)

每行最大的三个值的索引：
[[3 2 6]
 [0 6 4]
 [4 3 7]
 [6 2 4]
 [6 5 4]
 [3 6 2]
 [1 6 3]
 [7 5 6]]
[[0.16666667 0.20833333 0.33333333]
 [0.16129032 0.19354839 0.29032258]
 [0.1372549  0.17647059 0.17647059]
 [0.14545455 0.16363636 0.16363636]
 [0.14634146 0.17073171 0.2195122 ]
 [0.175      0.175      0.2       ]
 [0.17647059 0.20588235 0.23529412]
 [0.18421053 0.23684211 0.23684211]]


In [3]:
largest_three_per_row = np.take_along_axis(ratios, sorted_indices_per_row, axis = 1)
print("每行最大的三个值：")
print(largest_three_per_row)

每行最大的三个值：
[[0.16666667 0.20833333 0.33333333]
 [0.16129032 0.19354839 0.29032258]
 [0.1372549  0.17647059 0.17647059]
 [0.14545455 0.16363636 0.16363636]
 [0.14634146 0.17073171 0.2195122 ]
 [0.175      0.175      0.2       ]
 [0.17647059 0.20588235 0.23529412]
 [0.18421053 0.23684211 0.23684211]]
